name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  alire-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: alire-project/setup-alire@v5
      - name: Build and test
        run: |
          alr build
          alr test
